export const convertCountryIntoCode = (countryName) => {
  switch (countryName) {
    case "Afghanistan":
      return "AF";
    case "Albania":
      return "AL";
    case "Algeria":
      return "DZ";
    case "Andorra":
      return "AD";
    case "Angola":
      return "AO";
    case "Antigua and Barbuda":
      return "AG";
    case "Argentina":
      return "AR";
    case "Armenia":
      return "AM";
    case "Australia":
      return "AU";
    case "Austria":
      return "AT";
    case "Azerbaijan":
      return "AZ";
    case "Bahamas":
      return "BS";
    case "Bahrain":
      return "BH";
    case "Bangladesh":
      return "BD";
    case "Barbados":
      return "BB";
    case "Belarus":
      return "BY";
    case "Belgium":
      return "BE";
    case "Belize":
      return "BZ";
    case "Benin":
      return "BJ";
    case "Bhutan":
      return "BT";
    case "Bolivia":
      return "BO";
    case "Bosnia and Herzegovina":
      return "BA";
    case "Botswana":
      return "BW";
    case "Brazil":
      return "BR";
    case "Brunei Darussalam":
      return "BN";
    case "Bulgaria":
      return "BG";
    case "Burkina Faso":
      return "BF";
    case "Burundi":
      return "BI";
    case "Cabo Verde":
      return "CV";
    case "Cambodia":
      return "KH";
    case "Cameroon":
      return "CM";
    case "Canada":
      return "CA";
    case "Central African Republic":
      return "CF";
    case "Chad":
      return "TD";
    case "Chile":
      return "CL";
    case "China":
      return "CN";
    case "Colombia":
      return "CO";
    case "Comoros":
      return "KM";
    case "Congo":
      return "CG";
    case "Congo, Democratic Republic of the":
      return "CD";
    case "Costa Rica":
      return "CR";
    case "Croatia":
      return "HR";
    case "Cuba":
      return "CU";
    case "Cyprus":
      return "CY";
    case "Czech Republic":
      return "CZ";
    case "Denmark":
      return "DK";
    case "Djibouti":
      return "DJ";
    case "Dominica":
      return "DM";
    case "Dominican Republic":
      return "DO";
    case "Ecuador":
      return "EC";
    case "Egypt":
      return "EG";
    case "El Salvador":
      return "SV";
    case "Equatorial Guinea":
      return "GQ";
    case "Eritrea":
      return "ER";
    case "Estonia":
      return "EE";
    case "Eswatini":
      return "SZ";
    case "Ethiopia":
      return "ET";
    case "Fiji":
      return "FJ";
    case "Finland":
      return "FI";
    case "France":
      return "FR";
    case "Gabon":
      return "GA";
    case "Gambia":
      return "GM";
    case "Georgia":
      return "GE";
    case "Germany":
      return "DE";
    case "Ghana":
      return "GH";
    case "Greece":
      return "GR";
    case "Grenada":
      return "GD";
    case "Guatemala":
      return "GT";
    case "Guinea":
      return "GN";
    case "Guinea-Bissau":
      return "GW";
    case "Guyana":
      return "GY";
    case "Haiti":
      return "HT";
    case "Honduras":
      return "HN";
    case "Hungary":
      return "HU";
    case "Iceland":
      return "IS";
    case "India":
      return "IN";
    case "Indonesia":
      return "ID";
    case "Iran":
      return "IR";
    case "Iraq":
      return "IQ";
    case "Ireland":
      return "IE";
    case "Israel":
      return "IL";
    case "Italy":
      return "IT";
    case "Jamaica":
      return "JM";
    case "Japan":
      return "JP";
    case "Jordan":
      return "JO";
    case "Kazakhstan":
      return "KZ";
    case "Kenya":
      return "KE";
    case "Kiribati":
      return "KI";
    case "Korea, Democratic People's Republic of":
      return "KP";
    case "Korea, Republic of":
      return "KR";
    case "Kuwait":
      return "KW";
    case "Kyrgyzstan":
      return "KG";
    case "Lao People's Democratic Republic":
      return "LA";
    case "Latvia":
      return "LV";
    case "Lebanon":
      return "LB";
    case "Lesotho":
      return "LS";
    case "Liberia":
      return "LR";
    case "Libya":
      return "LY";
    case "Liechtenstein":
      return "LI";
    case "Lithuania":
      return "LT";
    case "Luxembourg":
      return "LU";
    case "Madagascar":
      return "MG";
    case "Malawi":
      return "MW";
    case "Malaysia":
      return "MY";
    case "Maldives":
      return "MV";
    case "Mali":
      return "ML";
    case "Malta":
      return "MT";
    case "Marshall Islands":
      return "MH";
    case "Mauritania":
      return "MR";
    case "Mauritius":
      return "MU";
    case "Mexico":
      return "MX";
    case "Micronesia (Federated States of)":
      return "FM";
    case "Moldova":
      return "MD";
    case "Monaco":
      return "MC";
    case "Mongolia":
      return "MN";
    case "Montenegro":
      return "ME";
    case "Morocco":
      return "MA";
    case "Mozambique":
      return "MZ";
    case "Myanmar":
      return "MM";
    case "Namibia":
      return "NA";
    case "Nauru":
      return "NR";
    case "Nepal":
      return "NP";
    case "Netherlands":
      return "NL";
    case "New Zealand":
      return "NZ";
    case "Nicaragua":
      return "NI";
    case "Niger":
      return "NE";
    case "Nigeria":
      return "NG";
    case "North Macedonia":
      return "MK";
    case "Norway":
      return "NO";
    case "Oman":
      return "OM";
    case "Pakistan":
      return "PK";
    case "Palau":
      return "PW";
    case "Palestine, State of":
      return "PS";
    case "Panama":
      return "PA";
    case "Papua New Guinea":
      return "PG";
    case "Paraguay":
      return "PY";
    case "Peru":
      return "PE";
    case "Philippines":
      return "PH";
    case "Poland":
      return "PL";
    case "Portugal":
      return "PT";
    case "Qatar":
      return "QA";
    default:
      return "Country not found";
  }
};
